#!/bin/bash

container_label=l12o-repo

container_dir="$(dirname ${0})/../container"


echo "pwd: $(pwd)"
echo "container_label: ${container_label}"
echo "container_dir: ${container_dir}"

cd ${container_dir}/../

pwd
echo

docker build \
  --file ${container_dir}/Dockerfile \
  --tag ${container_label}:latest \
  --label ${container_label} \
  .

docker image prune \
  --force \
  --filter="label=${container_label}"
